<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DocumentationFile></DocumentationFile>
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AgileConfig.Client" Version="1.7.6" />
		<PackageReference Include="Cronos" Version="0.8.4" />
		<PackageReference Include="DotNetCore.CAP.Dashboard" Version="8.1.2" />
		<PackageReference Include="DotNetCore.CAP.InMemoryStorage" Version="8.1.2" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.20.1" />
		<PackageReference Include="Savorboard.CAP.InMemoryMessageQueue" Version="8.0.0" />
		<PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.8" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="DaLang.Lims.Web.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\framework\DaLang.Lims.Web.Framework\DaLang.Lims.Web.Framework.csproj" />
		<ProjectReference Include="..\..\framework\DaLang.Lims.Web.ApiUI\DaLang.Lims.Web.ApiUI.csproj" />
		<ProjectReference Include="..\..\framework\DaLang.Lims.Web.Module.Dev\DaLang.Lims.Web.Dev.csproj" />
		<ProjectReference Include="..\..\modules\BasicData\DaLang.Lims.BaseData.Application\DaLang.Lims.BaseData.Application.csproj" />
		<ProjectReference Include="..\..\modules\Exam\DaLang.Lims.Exam.Application\DaLang.Lims.Exam.Application.csproj" />
		<ProjectReference Include="..\..\modules\OpenSlide\DaLang.Lims.OpenSlide.Application\DaLang.Lims.OpenSlide.Application.csproj" />
		<ProjectReference Include="..\..\modules\Pathology\DaLang.Lims.Pathology.Application\DaLang.Lims.Pathology.Application.csproj" />
		<ProjectReference Include="..\..\modules\Pretreatment\DaLang.Lims.Pretreatment.Application\DaLang.Lims.Pretreatment.Application.csproj" />
		<ProjectReference Include="..\..\modules\ReportTemplate\DaLang.Lims.ReportTemplate.Application\DaLang.Lims.ReportTemplate.Application.csproj" />
		<ProjectReference Include="..\..\modules\Statistics\DaLang.Lims.Statistics.Application\DaLang.Lims.Statistics.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="wwwroot\*\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\*\*\*\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\*\*\*\*\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<Content Update="Configs\appconfig.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Configs\dbconfig.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Update="Configs\ratelimitconfig.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
		<Content Update="Configs\ratelimitconfig.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\upload\" />
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties />
		</VisualStudio>
	</ProjectExtensions>
</Project>
