<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI" Version="1.17.0" />
		<PackageReference Include="Microsoft.Agents.AI.Hosting" Version="1.17.0-preview.260804.1" />
		<PackageReference Include="Microsoft.Agents.AI.Hosting.OpenAI" Version="1.17.0-alpha.260804.1" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.17.0" />
		<PackageReference Include="AspectCore.Extensions.DependencyInjection" Version="2.4.0" />
	</ItemGroup>
</Project>
